
services:
  backend:
    image: sm-app
    build:
      context: .
      target: production-image
    container_name: sm-app
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SMART_MONITOR_DB_HOST: "sm-db"

  postgres:
    image: postgres:17-alpine
    container_name: sm-db
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${SMART_MONITOR_DB_USER}
      POSTGRES_PASSWORD: ${SMART_MONITOR_DB_PASSWORD}
      POSTGRES_DB: ${SMART_MONITOR_DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SMART_MONITOR_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
