FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package.json frontend/yarn.lock frontend/.pnp.cjs frontend/.pnp.loader.mjs ./

RUN corepack enable yarn

COPY frontend/ .

RUN yarn install

RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/dist/spa /usr/share/nginx/html

COPY deploy/nginx.template.conf /etc/nginx/nginx.template.conf
COPY deploy/nginx-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]