FROM python:3.14-slim AS builder

ARG INSTALL_DEV=false

ENV PATH="/venv/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_CACHE_DIR=/root/.cache/uv \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_NO_MANAGED_PYTHON=1 \
    UV_PROJECT_ENVIRONMENT=/venv \
    UV_PYTHON_DOWNLOADS=never \
    UV_REQUIRE_HASHES=0 \
    UV_VERIFY_HASHES=1 \
    VIRTUAL_ENV=/venv


COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /backend

COPY backend/pyproject.toml .

RUN --mount=type=cache,target=/root/.cache/uv \
    uv venv $VIRTUAL_ENV && \
    if [ "$INSTALL_DEV" = "true" ]; then \
        uv sync --no-editable --group dev; \
    else \
        uv sync --no-editable --no-group dev; \
    fi

FROM python:3.14-slim AS production-image

ENV TZ=Europe/Moscow

RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && rm -rf /var/lib/apt/lists/*


ENV PATH="/venv/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    VIRTUAL_ENV=/venv \
    PYTHONPATH="/backend"

WORKDIR /backend
COPY --link --from=builder /venv /venv
COPY backend/app /backend/app
EXPOSE 8000
RUN chmod +x /backend/app/start.sh
ENTRYPOINT ["/backend/app/start.sh"]

FROM python:3.14-slim AS testing-image

ENV TZ=Europe/Moscow
RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/venv/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    VIRTUAL_ENV=/venv \
    PYTHONPATH="/backend" \
    TESTING=true

WORKDIR /backend
COPY --link --from=builder /venv /venv
COPY backend/app /backend/app
COPY backend/tests /backend/tests

RUN chmod +x /backend/app/start-testing.sh
ENTRYPOINT ["/backend/app/start-testing.sh"]

